--- #YAML:1.0
name:               XML-ASCX12
version:            0.04
abstract:           ASCX12 EDI to XML Module
author:
    - Brian Kaney <brian@vermonster.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/bkaney/perl-XML-ASCX12
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
